### PR TITLE
Add ability to set user status and get another users status

### PR DESCRIPTION
**Pull request by RogerSelwyn**
Add ability to set user presence status per application and set user preferred presence status, plus get another users presence status

Get my presence status is currently under Teams, so I have placed these there as well

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
Blimey that was fast!! Do you know when you will release?

**Comment by alejcas** [comment]
expect a release this week

**Comment by RogerSelwyn** [comment]
Cool. looked like you were getting ready.

**Comment by RogerSelwyn** [comment]
Just a comment, currently I can't move to a latest release because of this error - https://github.com/O365/python-o365/issues/1011


Unfortunately I only just looked at it again after a couple of months. You noted the issue as fixed, but is seems I still can't pass in a timezone as a string.

**Comment by RogerSelwyn** [comment]
> Released 2.0.32

Thanks. Have you noted my problem with doing anything with setting dates? https://github.com/O365/python-o365/issues/1011

**Comment by alejcas** [comment]
> > Released 2.0.32
> 
> Thanks. Have you noted my problem with doing anything with setting dates? #1011

Yes, but no clue for the moment

**Comment by RogerSelwyn** [comment]
> Yes, but no clue for the moment

Are you able to replicate? I don't know whether it is just me... I've put some sample code on the issue. If you can replicate, then I know it's not just me being stupid :-(.

**Pull request merged**
