### PR TITLE
Added ability to set/ disable auto reply

### PR DESCRIPTION
**Pull request by lodesmets**
These changes allow to set/ disable the auto reply.
With this you can schedule the auto reply functionality in outlook

### CODE REVIEW

**Comment by janscas** [comment]
Great addition! thanks!

**Comment by RogerSelwyn** [comment]
@lodesmets & @janscas This PR broke many of the Mailbox endpoints by overriding the Folder endpoints array. Consequently a call to Mailbox.get_folders() no longer works, along with a number of others. `_endpoints` in `Mailbox` needs to be added to those from `Folder`.

**Comment by lodesmets** [comment]
> @lodesmets & @janscas This PR broke many of the Mailbox endpoints by overriding the Folder endpoints array. Consequently a call to Mailbox.get_folders() no longer works, along with a number of others. `_endpoints` in `Mailbox` needs to be added to those from `Folder`.

I'm terribly sorry for breaking the feature. I didn't notice that mailbox (unlike other classes wasn't a child of ApiComponent).
But I noticed you already added a PR for the fix

**Comment by janscas** [comment]
@RogerSelwyn true! I didn’t even notice… i’m sorry

@lodesmets don’t worry this happens…

**Pull request merged**
