### PR TITLE
fixing itemAt endpoint to new structure

### PR DESCRIPTION
**Pull request by ShadiNM**
Table Row operations are not aligned anymore with Microsoft Graph Docs 
https://learn.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&tabs=http

See also here, but this did not fully fix the issue
https://github.com/O365/python-o365/pull/849

could you please review and merge if this is fine?

### CODE REVIEW

**Comment by ShadiNM** [comment]
@alejcas is everything ok with this change?

**Comment by alejcas** [comment]
Thanks!

**Comment by ShadiNM** [comment]
@alejcas thanks for merging! Could you let me know when this will be released to PyPI as version 2.0.37?
I would like to use the newest changes in my project

**Comment by alejcas** [comment]
I've just released 2.0.37

**Pull request merged**
