### PR TITLE
Fix SharePoint `search_site` with more than 200 results

### PR DESCRIPTION
**Pull request by thaiphv**
As titled.

### CODE REVIEW

**Comment by thaiphv** [comment]
@janscas what do you think about this change?

**Comment by janscas** [comment]
> @janscas what do you think about this change?

Hi, it’s ok, but there’s a Pagination object in the utils directory that will be more efficient. Your code will retrieve all the records even if you just need a few.

**Comment by janscas** [comment]
I’ll merge this anyway

**Comment by thaiphv** [comment]
Thanks. When will you make another release to PyPi?

**Comment by thaiphv** [comment]
@janscas can you please publish it to PyPI?

**Comment by janscas** [comment]
@thaiphv  Cleaning PRs and publishing now

**Pull request merged**
