### PR TITLE
Sharepoint Docs Draft

### PR DESCRIPTION
**Pull request by jtweeder**
Here is the first pass at the Sharepoint docs.  I have the HTML build from make html output, but I was not sure how you wanted to review the proposed documentation, and if there was already a process in place to build the new documentation.

After you review, just let me know if you want me to add in the entire HTML build output, parts of it, or just these .rst file changes if you had plans on making other updates to the docs.

### CODE REVIEW

**Comment by janscas** [comment]
I don't know how to roll this into the docs. This part was handled by @roycem90 

Let's wait a bit

**Comment by stardust85** [comment]
I like that pull request (however I'm not an expert on writing docs - but who is?). It is better than no docs :D I'm working on file uploads and downloads as a user of this library now so if time permits (I don't want to promiss anything) I can improve it later by adding something about working with files

**Comment by stardust85** [comment]
related issue: https://github.com/O365/python-o365/issues/409

**Comment by stardust85** [comment]
so basically we will need to merge this first so we don't have a conflict...

**Comment by janscas** [comment]
I look @GeethanadhP never review this.  I'll merge this.

**Comment by stardust85** [comment]
Thanks for merging. Actually I managed to do my job with the library I used before (https://github.com/vgrem/Office365-REST-Python-Client) but in long term I would like to switch to yours because Office365-REST-Python-Client has inconvenient APIs

**Pull request merged**
