### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by roycem90**
Only added some, but just want you @Narcolapser  get the setup done in settings, so we can see how it looks..

More coming..

### CODE REVIEW

**Comment by Narcolapser** [comment]
Ok, I think I've flipped the appropriate switches. I've tentatively selected Slate as the documentation theme. If anyone has a strong opinion on the theme feel free to suggest it. I literally just looked at the ten and thought "eh, that looks nice." So I'm open to suggestions.

**Comment by roycem90** [comment]
what theme?
this docs comes with html in readthedocs format

**Comment by roycem90** [comment]
Settings > Github Pages > Source > master branch /docs
use the /docs not the master

after u change it have a look at https://o365.github.io/python-o365/

**Comment by Narcolapser** [comment]
Apparently theme only matters if your documentation is nothing but a readme.

**Pull request merged**
