### PR TITLE
Added support for tasks/todo via MS Graph API

### PR DESCRIPTION
**Pull request by RogerSelwyn**
As promised here is a MS Graph api version of the Tasks/ToDo.

At this time, I've:
- implemented as a new class file `tasks_graph.py`, primarily because my formatting style on VSCode will re-format the rest of the code in `tasks.py`. I can copy the code into the original class file and rename the classes to names such as `ToDoGraph` if you wish.
- renamed a couple of attributes. (e.g. in the Graph api it uses `title` for the task, rather than `subject`). Also some constants are now all lower case (e.g. `Completed` has become `completed`).
- endpoints to constants - I'm paranoid about not matching things up. I can change back if preferred.
- tried to exercise all routes through the code. So hopefully no problems
- implemented a filter capability on `get_tasks` not present in existing code. This allows you to get uncompleted tasks for instance.

I think in passing I have fixed some issues that existing in MS Office implementation. Certainly there was at least one redundant endpoint, but I think there was at least one utilised endpoint that didn't have the relevant parameters passed to it. I'd have to go back and try and test using Office API to validate that statement. 

There seems to be no existing documentation for Tasks. I can potentially add something to the Readme if you like. Or have a looks at how the generated docs work to see if it will generate meaningfully.

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
I should add whilst the code is very similar to the Office APIs version, there are variations throughout. Some outlined above, but also items such as how the Graph Api identifies the default folder (for which there is no longer a straight API call, you have to retrieve all and enumerate - I can probably improve that ny using a filter on the relevant attribute).

**Comment by janscas** [comment]
Hi, thanks for this PR.

Great work and thanks for updating the readme!

As for your comments:

- I don't mind having this in a separate file. So it's ok as it is now.
- About the different attribute names between Graph and Office protocols I would like to unite them but It's ok for the moment as it is.
- About the other api differences, O365 should try to do the best for the user and seems it's already doing that. Maybe you could catch the default folder but it won't probably make any difference in many use cases.
- Using constants for the endpoints keys is a great addition,

**Comment by janscas** [comment]
I'm going to release a new version now with these changes

**Comment by RogerSelwyn** [comment]
If you wait to tomorrow I can change back the different attribute names. I thought about doing it this morning.

**Comment by janscas** [comment]
Ok great!
I'll commit a few pep8 fixes to your code

**Comment by RogerSelwyn** [comment]
Ok, I don’t use pep8. Home Assistant uses flake8 and black. 

The code supports default_folder. I need to check what I’ve done with Status, probably add an enumerator or something to keep it the same as O365.

**Comment by janscas** [comment]
a few fixes here: 9702c3b225ffcd3ef712fddffe27d1908b847012

**Comment by RogerSelwyn** [comment]
I’ll need to do a new PR I think?

**Comment by janscas** [comment]
> I’ll need to do a new PR I think?

yep

**Pull request merged**
