### PR TITLE
Add access to singleValueExtendedProperties in Message

### PR DESCRIPTION
**Pull request by svmcaro**
Added single_value_extended_properties instance attribute and property so singleValueExtendedProperties can be accessed. This allows you to get information like the message size (singleValueExtendedProperty id LONG 0x0E08)

### CODE REVIEW

**Comment by janscas** [comment]
Thanks

**Comment by svmcaro** [comment]
> Thanks

Thanks for merging @janscas. Do you have a date for when you plan to release a new version with the latest changes included?

**Comment by janscas** [comment]
a few days

**Comment by janscas** [comment]
done

**Pull request merged**
