### PR TITLE
added proxy_http_only flag for Connection

### LINKED ISSUE #616: https proxy starting by 'http://'
Hi O365 team.

Thank you for your job on this librairy.

To communicate with internet (and graph.microsoft.com), my code must pass through a proxy. For http and https communication, the protocol is the same: http://
http_proxy : http://proxy.company.com
https_proxy : http://proxy.company.com

However, [in your code, https protocol is hardcoded](https://github.com/O365/python-o365/blob/7bab7798c7d952c47a089878fed0630466ea7fb9/O365/connection.py#L428).

To correct this little issue, I propose you this code:
```python
    def set_proxy(self, proxy_server, proxy_port, proxy_username,
                  proxy_password, proxy_https_protocol="https"):
        """ Sets a proxy on the Session
        :param str proxy_server: the proxy server
        :param int proxy_port: the proxy port, defaults to 8080
        :param str proxy_username: the proxy username
        :param str proxy_password: the proxy password
		:param str proxy_https_protocol: the protocol to access to https proxy,
		                                 defaults is https
        """
        if proxy_server and proxy_port:
            if proxy_username and proxy_password:
    		    self.proxy = {
                    "http": "http://{}:{}@{}:{}".format(proxy_username,
                                                        proxy_password,
                                                        proxy_server,
                                                        proxy_port),
                    "https": "{}://{}:{}@{}:{}".format(proxy_https_protocol,
                                                       proxy_username,
                                                       proxy_password,
                                                       proxy_server,
                                                       proxy_port),
                }
			
            else:
                self.proxy = {
                    "http": "http://{}:{}".format(proxy_server, proxy_port),
                    "https": "{}://{}:{}".format(proxy_https_protocol, proxy_server, proxy_port),
                }
```

Thank you in advance for your interest.

### PR DESCRIPTION
**Pull request by senor-vu**
Allows user to set and http url for both http and https requests.
There are organizations and users that only have an http proxy instead of a proxy that does ssl intercept.

Fixes #616

### CODE REVIEW

**Comment by janscas** [comment]
Thanks!

**Comment by senor-vu** [comment]
No problem! When does this get updated in pypi?

**Comment by janscas** [comment]
I’m out for a few days. I’ll release asap

**Comment by senor-vu** [comment]
Hey @janscas just wanted to see if when the next release is coming

**Comment by janscas** [comment]
@senor-vu  Releasing today

**Pull request merged**
