### PR TITLE
Planner and tasks

### PR DESCRIPTION
**Pull request by AnoojNair**
PR for planner related features like tasks

### CODE REVIEW

**Comment by roycem90** [comment]
@AnoojNair i hope this has been tested?

**Comment by Narcolapser** [comment]
It is the right scope so we'd be happy to include the code. I downloaded it and fiddled with the code some myself. Unfortunately I am not an administrator so I cannot consent to the permissions needed to use this portion of the API. So I can't speak to it's functionality, but it looks right.

Because it is not intuitive can you include in the comments some where what [permissions](https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0) are needed to get this portion of the API to work?

Bonus points if you can write some tests for this class. Cheers!

**Comment by janscas** [comment]
As @Narcolapser said, I also can't test this because I can't set app permissions (just delegated permissions).

But the code looks fine as @Narcolapser  said.

**Comment by AnoojNair** [comment]
@Narcolapser @janscas @roycem90  . Thanks for the feedback. I will include tests and documentation into the PR as well

**Comment by AnoojNair** [comment]
@Narcolapser , Just wanted to check how the o365_token.txt gets populated? i wanted to check what would be the minimum permission required to read user's tasks. i feel it should be 'Tasks.Read' . 

Each time i authenticate, the token.txt file has all these scopes

"https://graph.microsoft.com/Group.Read.All",
  "https://graph.microsoft.com/Mail.ReadWrite",
  "https://graph.microsoft.com/Mail.Send",
  "https://graph.microsoft.com/Sites.Read.All",
  "https://graph.microsoft.com/Tasks.Read",
  "https://graph.microsoft.com/User.Read"

i tried removing them all and just keeping Tasks.Read. and authenticate again using 
result = acc.authenticate(scopes=['Tasks.Read'])

then it re-populates back to

 "scope": [
  "profile",
  "openid",
  "email",
  "https://graph.microsoft.com/Group.Read.All",
  "https://graph.microsoft.com/Mail.ReadWrite",
  "https://graph.microsoft.com/Mail.Send",
  "https://graph.microsoft.com/Sites.Read.All",
  "https://graph.microsoft.com/Tasks.Read",
  "https://graph.microsoft.com/User.Read"
 ]

Please let me know if i am missing something. i haven't adding any permission in the registration portal as of yet.

image

**Comment by janscas** [comment]
I think that’s because you have previously consent that app with those scopes. 

Remove the app and make it again. You will have to change the client id and client secret.

**Comment by AnoojNair** [comment]
Thanks @janscas . I am trying to write some unit tests for planner, but when i run py.test i get the modulenotfounderror for O365. Am i missing something?

image

**Comment by roycem90** [comment]
try installing it 
(run this from your git repo, that will install O365 by linking to your code location)
pip install -e ./

**Comment by AnoojNair** [comment]
Thanks @roycem90 . Also guys @janscas @Narcolapser . I have included tests for planner .But the return value is always None. I am not sure how to complete the oauth flow while the test executes as the oath flow requires me to paste the url from the browser.

Please let me know if am missing something in the test class.

**Comment by roycem90** [comment]
@AnoojNair u need not get the data from original account (that part is separate you do a manual test for those stuff, that is what we do most of the time when we make changes)

these tests that you are adding are automated py tests.. we generally create mocks 
from unittest.mock import MagicMock and mock patching or 
manual mocking, below is how we do manual mock

- Get a sample response (probably the one here - https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0)
- Save it to a planner_my_tasks.json under tests/samples dir

`
    import json

    class MockResponse:
        resp_file = None

        def json(self):
            with open(MockResponse.resp_file) as f:
                resp_json = json.load(f)
            return resp_json

    class MockConnection:
        def get(self, url, params=None, **kwargs):
            self.url = url
            self.kwargs = kwargs
            return MockResponse()
    
   
    def test_get_my_tasks(self):
        MockResponse.resp_file = 'planner_my_tasks.json'
        # after this as your connection returns a valid json, your planner class should do the rest
`

**Comment by AnoojNair** [comment]
Thanks @roycem90 , Are there any sample mock tests in the project that i can check and create mock test similarly?

**Comment by roycem90** [comment]
don't think we wrote any tests properly, you can use that code i added above i guess it works, or just to do manual tests and push the code once you are sure all is good :)

**Comment by roycem90** [comment]
can you do a commit commenting out the test (that is failing, would like green :) )

@janscas @Narcolapser code seems fine, i m ok to merge this

**Comment by janscas** [comment]
Seems ok to me also

**Comment by nguyenl95** [comment]
can anyone write unittests for this?

**Comment by janscas** [comment]
Instead of asking, do it yourself

**Pull request merged**
