### PR TITLE
Added field query for SharePoint lists.

### PR DESCRIPTION
**Pull request by jrmatchett**
Added `on_list_field` method to the `Query` class in order to correctly filter a SharePoint list by its fields.

### CODE REVIEW

**Comment by janscas** [comment]
Thanks

**Comment by elmorejd** [comment]
Would you be able to provide an example of a query filter for a sharepoint list? something to the effect of limiting items that contain a specific string within a specific column.

**Comment by jrmatchett** [comment]
@elmorejd Here's an example:
```
query = my_list.q().expand('fields').select('Field1', 'Field2', 'Field3')
query.chain().on_list_field('Field1').equals('some_value')
items = my_list.get_items(query=query)
```

**Comment by jsormaz** [comment]
> @elmorejd Here's an example:
> 
> ```
> query = my_list.q().expand('fields').select('Field1', 'Field2', 'Field3')
> query.chain().on_list_field('Field1').equals('some_value')
> items = my_list.get_items(query=query)
> ```

does this still work? I can't seem to get it to work.

**Comment by jsormaz** [comment]
> > @elmorejd Here's an example:
> > ```
> > query = my_list.q().expand('fields').select('Field1', 'Field2', 'Field3')
> > query.chain().on_list_field('Field1').equals('some_value')
> > items = my_list.get_items(query=query)
> > ```
> 
> does this still work? I can't seem to get it to work.

to add more detail,
I got this to work filtering on a lookupid field. I cannot get it to work filtering by the string value of the "Title" field

**Comment by jsormaz** [comment]
> > > @elmorejd Here's an example:
> > > ```
> > > query = my_list.q().expand('fields').select('Field1', 'Field2', 'Field3')
> > > query.chain().on_list_field('Field1').equals('some_value')
> > > items = my_list.get_items(query=query)
> > > ```
> > 
> > 
> > does this still work? I can't seem to get it to work.
> 
> to add more detail,
> I got this to work filtering on a lookupid field. I cannot get it to work filtering by the string value of the "Title" field

I had to make the column an "indexed column" to be able to filter on it.

**Pull request merged**
