### PR TITLE
Update connection.py to allow default_headers to allow immutable ID

### PR DESCRIPTION
**Pull request by yeyeric**
Allow to set default_headers when creating account so that those params are sent.
Typical usage is default_headers={"Prefer": 'IdType="ImmutableId"'} which allows to have permanent immutable id instead of default temporary ID which changes as soon as the object (message / event / task / contact) gets moved / updated.

### CODE REVIEW

**Comment by yeyeric** [comment]
hi @janscas , do you think this can be merged or needs further review ? this update is important for my project so that'd be great
Thanks

**Comment by yeyeric** [comment]
hello @janscas , can this be pushed through or any specific procedure to follow  (first PR for me on a public repo) ?
thanks

**Comment by janscas** [comment]
Hi, first, thanks for this PR.

For me it's ok, but I don't have the time to test this.

Hope you did!

**Comment by janscas** [comment]
2.0.26 released

**Pull request merged**
