### PR TITLE
fixed empty post data error

### PR DESCRIPTION
**Pull request by cccmir**
added None check to data before json conversion.
json converts None into 'null' which is not a valid json

### CODE REVIEW

**Comment by motyp** [comment]
@cccmir Thanks.

**Comment by janscas** [comment]
@cccmir What is this solving exactly?

Is this related to a bug?

Can you further explain this?

Thanks

**Comment by cccmir** [comment]
@janscas 
Yeah sorry i didn't open an issue.

when using message.reply i get the following error:

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://outlook.office.com/api/v2.0/me/messages/{messageid}/createReply | Error Message: An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.

**Comment by janscas** [comment]
ok, got it.

**Comment by janscas** [comment]
This will be included in the v1.1.9 version

**Pull request merged**
