### PR TITLE
Group drive

### PR DESCRIPTION
**Pull request by tino-247**

### CODE REVIEW

**Comment by tino-247** [comment]
@GeethanadhP @janscas let me know what you think about those changes

**Comment by janscas** [comment]
commit dab0940e2d5955d36b6fb651f46b04a24c4b4f5d is usefull and can be merged

**Comment by tino-247** [comment]
With
```
group_storage = account.storage(resource='group:xyz')
group_drives = group_storage.get_drives()
```
I'm getting
`{HTTPError}400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/group:xyz/drives?%24top=999 | Error Message: Resource not found for the segment 'group:xyz'.`

**Comment by GeethanadhP** [comment]
well i have been out of sync for a long time here :), so i will let @janscas  handle the stuff :100:

**Comment by janscas** [comment]
@tino-247 my bad!

I've committed a fix for this. It should work now with the changes on 9fc40f5b506a95e7fd4c95eab9a4c6b87bbb3f1f.

**Comment by tino-247** [comment]
@janscas I updated the PR.

**Pull request merged**
