### PR TITLE
Add support for filter by due datetime in Tasks

### PR DESCRIPTION
**Pull request by RogerSelwyn**
Added extra mapping in Utils to support filter by due datetime and reminder datetime in Tasks

Also added extra detail to connection error reporting <-- This can be removed if preferred but it provides extra information on why a call failed.

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
Do you know when you will release a new version with this included?

**Comment by janscas** [comment]
I can do it in a few days

**Comment by RogerSelwyn** [comment]
> I can do it in a few days

Thanks

**Comment by janscas** [comment]
done

**Comment by RogerSelwyn** [comment]
> done

Thanks

**Pull request merged**
