### PR TITLE
Extend AutoReply Configuration

### PR DESCRIPTION
**Pull request by RogerSelwyn**
This PR:
- Types the input parameters so as to accept datetime objects for start and end date
- Accepts start date and end date as optional, so as to allow auto reply to be AlwaysEnabled or Scheduled.

### CODE REVIEW

**Comment by janscas** [comment]
great

**Comment by RogerSelwyn** [comment]
@janscas do you know when you will do a new release. I just need to decide if I release my Home Assistant integration based on the older code base or wait for the new one. Thanks, Roger

**Comment by janscas** [comment]
Tomorrow?

**Comment by RogerSelwyn** [comment]
> @janscas do you know when you will do a new release. I just need to decide if I release my Home Assistant integration based on the older code base or wait for the new one. Thanks, Roger

That would be amazing. I'll work up the change for the integration in the morning.

**Comment by janscas** [comment]
Released 2.0.24

**Comment by RogerSelwyn** [comment]
> Released 2.0.24

Thanks

**Pull request merged**
